### ISSUE TITLE
Gpu Memory Used is Low?

### ISSUE THREAD

**Issue by NaveenGTK** [ashleykleynhans/runpod-worker-forge#2]
Hello, thank you very much for this. I currently have one question. When I deploy the pod my GPU utilization increases to 99% but my GPU memory used remains 32%. Is there a way I can use all of my GPU so I can get the full power of it and generate images faster? Is there a particular flag I should edit?

![image](https://github.com/ashleykleynhans/runpod-worker-forge/assets/115793005/52daffd5-f20a-45e0-a92f-41e4338f2810)

Thank you!

**Comment by ashleykleynhans** [comment]
Please don't log irrelevant stuff here, log it under Forge repo, this just runs Forge, I am not the developer of Forge!
